### ISSUE TITLE
How do I reverse the changes of this script?

### ISSUE THREAD

**Issue by Elliot87** [glenpike/npm-g_nosudo#15]
I tried using this script, both downloading it/running it, and using the wget method, but i still get EACCESS errors when trying to install packages globally. To make things even worse, with whatever this script did, I can now no longer use sudo npm commands, it returns error:  `/usr/bin/env: node: No such file or directory`the only way for me to run sudo npm commands now is to use an elevated terminal.

**Comment by glenpike** [comment]
Hi,

Sorry it messed up, hopefully the things below might help:

What OS are you running on?  Are you using nvm or any other version manager for Node? (nvm doesn't need the sudo fix as far as I know.)

The script will do the following, so you may be able to reverse the steps to fix your installation:

1. Save the list of "global" packages in /tmp/npm-reinstall.txt (this is removed at the end of the script though)
2. Remove the existing packages (except for npm)
3. Create the new package directory - this is ~/.npm-packages unless you told it to use somewhere else.
4. Set the npm configuration to use this directory to install packages - this did write to ~/.npmrc previously.
5. Change the ownership of all the files in ~/.npm to your user (from root)
6. Reinstall the packages that were listed in the tmp file.
7. Give you the option to update your environment variables in bash / zsh - after doing this, you still need to start a new terminal our run source ~/.bashrc for the variables to take effect.

I believe the default directory for installing npm packages on Ubuntu is /usr/local/lib/node_modules.

To shortcut a fix for this, you can look in your ~/.npm-packages/lib/node_modules dir to make a list of packages to reinstall manually - on Ubuntu you can use the following command to get a list of packages - you won't have the versions unless you look in each package.json file though.
```
ls ~/.npm-packages/lib/node_modules/ | tr -d ' '
``` 
You can then fix the config - edit ~/.npmrc and remove the prefix line, then try to reinstall your packages with sudo npm -g install ...
You may also have to remove the changes in your .bashrc / .zshrc file if you asked the system to do that.

Hope it helps.

**Comment by Elliot87** [comment]
Thanks. I forgot to mention I'm running Linux mint 17.2

And you'll have to forgive me, I'm very new to Linux, the only reason I switched was because I couldn't seem to get yeoman working properly on my windows7 so I figured I'd give it a shot on linux.

It's quite possible I messed up somewhere on the install,  but basically what I did was at first I tried running the command `./npm-g-nosudo.sh` and it  didnt run -- do I need to extract the zip or move the npm-g-nosudo.sh file to a specific directory before running the command?

After that, I tried just clicking on the .sh file and running it in the terminal from it's extracted location (which I admit I probably shouldn't have done) ...I had it extracted to the default location, /home/downloads and I ran it from inside the /home/downloads/npm-g_nosudo-master directory it extracted into. The script ran, and it said that it was installed, however when it got to the y/n part it just skipped straight by it, without waiting for me to input yes or no. This is the point where my sudo npm command became broken, and still got EACCESS errors without sudo.

From here I attempted to run the wget method in my command line, hoping it would overwrite whatever the previous script did, and remove my need to use sudo, but it was probably too late at this point if I had already messed up something prior to that.

Sorry for being a newb, but since I'm coming from a windows system prior to this, I don't have experience using the sudo command. Personally, It doesn't bother me having to use sudo sometimes, however that might just be because I'm a brand new linux user. I really need this to work though because according to the documentation for yeoman, it advises against using sudo to install, and pointed me here for a no-sudo fix. 

Sorry for any confusion, and thanks for the help, I've gotten sudo npm command working again, but I still really need to find out what I did wrong installing this, so if you can see where i possibly messed up, please do tell. I'm considering just trying the wget method first, now that my system is back to normal....it  seems to be the most straightforward method, no downloading/moving files required.

**Comment by Elliot87** [comment]
also, just to clarify, you're trying to say if i uninstall node and reinstall it via nvm, I won't have to use sudo anymore for global installs?

**Comment by glenpike** [comment]
I have not tried it, but I believe using nvm to manage multiple versions of nodejs means you don't have to use sudo for installing "global" packages - see this article.

http://www.nearform.com/nodecrunch/nodejs-sudo-free/

I only run a single version of nodejs - 2 different approaches.

**Comment by glenpike** [comment]
You might be able to fix your environment - it sounds like your ~/.bashrc file was not updated.  (Assuming your shell is bash - if you want to check your shell, run

```
ps -p $$
```
(from this page - http://www.cyberciti.biz/tips/how-do-i-find-out-what-shell-im-using.html)
You should see output something like:
```
PID TTY          TIME CMD
26856 pts/2    00:00:00 bash
```

If this is the case, you should be able to edit the file ~/.bashrc (in your home dir).  Run the following to check a couple of things:

```
cd ~
pwd
```
Make a note of the path output by pwd.

Now check your ~/.bashrc file:
```
cat ~/.bashrc
```
If it's not found, you need to create it - use:
```
touch ~/.bashrc
```
Otherwise, look for something like the following in the output:

NPM_PACKAGES="/home/glen.pike/.npm-packages"
NODE_PATH="$NPM_PACKAGES/lib/node_modules:$NODE_PATH"
PATH="$NPM_PACKAGES/bin:$PATH"
# Unset manpath so we can inherit from /etc/manpath via the `manpath`
# command
unset MANPATH  # delete if you already modified MANPATH elsewhere in your config
MANPATH="$NPM_PACKAGES/share/man:$(manpath)"

If it's not there, you need to add that - replacing "/home/glen.pike" with the path from pwd.
After changing that file you either start a new terminal session or run
```
. ~/.bashrc
```
This is shorthand for "source", which runs / loads that file into the current session - http://superuser.com/questions/46139/what-does-source-do.  (Any new sessions should get that automatically - you should check that works too).

Try that out and let me know if it sorts the problem.

**Comment by Elliot87** [comment]
1) Unfortunately the domain expired at http://www.nearform.com/nodecrunch/nodejs-sudo-free/ about 1 hour before I clicked it haha

2) Actually, since this is basically a brand new install of linux, I haven't done many modifications, so I don't have a bashrc file. The way I fixed this was just to delete both npmrc and bashrc because I didn't have them before. I will try to use nvm first, and if that doesn't work I'll try using this again. I tried using the wget method again from square one, but It gave some sort of repository error (literally spammed it) and then at the end gave some sort of http error 400, it might have been a network issue to be honest.....I wish I could give a better diagnosis, but I can't seem to find the npm-debug log it said it made. I was tired at the time so I just went to bed.

Can you clarify for me though please, since the wget method gave me a bunch of errors, I'll try the .sh file again.....but do I necessarily need to exract the npm_g-nosudo.sh to a certain directory before running it? Because last time I tried using the downloaded .sh file, when I tried to run it in the cmd it couldnt find it, and the only way I was able to run it was to click on it and click run in terminal, which is what messed everything up I think.

**Comment by glenpike** [comment]
If you download the raw file for npm_g-nosudo.sh - you can get it from here: https://raw.githubusercontent.com/glenpike/npm-g_nosudo/master/npm-g-nosudo.sh or click through from the file in the repo and click "Raw" to see it (it's just a shell script).  If you download / save that, you should not have to unzip it (that would be required if you clicked "Download Zip" on the right-hand-side).

Once downloaded, you can either make the script executable, then run it with:
chmod 755 npm-g-nosudo.sh
./npm-g-nosudo.sh

or ask the shell to run it:

sh ./npm-g-nosudo.sh

Someone else added the wget instruction - I've tried it, but personally, I am not too keen on running scripts like that because you may get errors, etc.

Hope that works - I am assuming you have Linux Mint bash shell as the default, so this _should_ work the same as my Ubuntu setup.

**Comment by Elliot87** [comment]
Do I need to save the shell script in the root directory?

**Comment by glenpike** [comment]
Doesn't matter where you put it - your home directory is best, e.g. ~

**Comment by Elliot87** [comment]
Thank you for your help. I decided to try nvm and I haven't had to use sudo yet. Still, thank you for helping me get things back to normal, and thanks for the tip on nvm. I'll go ahead and close this.
