### ISSUE TITLE
Didn't work When running the script with wget...  But did work when cloned and ran 

### ISSUE THREAD

**Issue by MrFoldAnyTen** [glenpike/npm-g_nosudo#22]
I don't really know what I'm doing but I used the wget install  last year and it worked i was using Ubuntu. Now I'm using Suse and I found running the script gave me the following errors

```
sh: line 142: syntax error near unexpected token `)'
sh: line 142: `    [Yy]* ) fix_env;;'
```

but when I cloned and ran it it ran fine.

**Comment by glenpike** [comment]
This looks a little like #6 - bash doesn't like the command, but Ubuntu sh is okay.

Did you pip the wget output straight to sh?  If so, what is your "sh" pointing at?

Can you try:

```
which sh | xargs ls -al
```
First part finds where your sh resides, 2nd part may tell you if it is a file or a symlink pointing to something else.  On my machine it says:

/bin/sh -> dash

I suspect your machine may be pointing at bash?

**Comment by MrFoldAnyTen** [comment]
Yes it would appear  that on my machine sh is pointing at bash.
    which sh | xargs ls -al
    /usr/bin/sh -> /bin/bash

Will this cause me further problems?
Is this related to other problems on my system running npm?

**Comment by glenpike** [comment]
Okay, your path to NPM packages may not be set in your environment.  You may need to add this to your .bashrc file (which is what the script tries to do when it failed on your machine).

I expect your npm-packages dir is located at ${HOME}/.npm-packages 
Check with:
```
ls -al ${HOME}/.npm-packages
```
If it's not there, it will give you an error message, otherwise a directory listing.

If you the follow the instructions from number 3 in Sindresorhus guide - https://github.com/sindresorhus/guides/blob/master/npm-global-without-sudo.md#3-ensure-npm-will-find-installed-binaries-and-man-pages-add-the-following-to-your-bashrczshrc - you can update your bashrc to point to that directory.  You will then need to start a new shell and check that it's working.  Quickest is to try 

```
npm config list
```
the output from that should tell you your prefix is set to the path from above.

Hope that helps.

I will see if there's a more cross-shell way of doing the case / esac thing.

**Comment by MrFoldAnyTen** [comment]
That's great.
I think I have npm working now, having tried all 3 methods; running the script, changing the npm prefix and changing permissions.
 I've followed a few different posts so have changed both my .profile and .bashrc files.

.bashrc:

export NPM_PACKAGES="/home/dylan/.npm-packages"
export NODE_PATH="$NPM_PACKAGES/lib/node_modules${NODE_PATH:+:$NODE_PATH}"
export PATH="$NPM_PACKAGES/bin:$PATH"
# Unset manpath so we can inherit from /etc/manpath via the `manpath`
# command
unset MANPATH  # delete if you already modified MANPATH elsewhere in your config
export MANPATH="$NPM_PACKAGES/share/man:$(manpath)"

export NVM_DIR="/home/dylan/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

.profile:

export PATH="$HOME/.node_modules_global/bin:$PATH"
export PATH=~/.npm-global/bin:$PATH

So I've hacked it I did say I don't know what I'm doing.
Notice I've also put nvm in for good measure.


[dylan@linux-uv1i ~]$ npm config list
; cli configs
user-agent = "npm/3.5.2 node/v4.2.1 linux x64"

; userconfig /home/dylan/.npmrc
prefix = "/home/dylan/.npm-global"

; node bin location = /usr/bin/node
; cwd = /home/dylan
; HOME = /home/dylan
; "npm config ls -l" to show all defaults.

**Comment by glenpike** [comment]
Okay, glad it's sorted.  I'm not sure if nvm plays nicely with this setup - I think you're supposed to leave it "global", but I've not tried, so be aware of that possible gotcha.

I think I'll leave this bug open and see about changing the script to play nicer.
